[package]
name = "macvenderator"
version = "0.1.0"
authors = ["Jade Angrboða <jade@trashwitch.dev>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
oui = "0.7"
